name: build-and-push-image
on: [push]

jobs:

  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: action image
      run: |
        cd $GITHUB_WORKSPACE
        echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
        docker build -t robin0f7/cicd-app-token -f Dockerfile .
        docker push robin0f7/cicd-app-token
      env:
        USERNAME: ${{ secrets.CICD_APP_DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.CICD_APP_DOCKER_PASSWORD }}
